remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-mentions
- jemoji
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-spaceship
- jekyll-archives
- jekyll-compose